name = "lean-ratfunc-witt-local-global"
version = "0.1.0"
keywords = ["math", "lean", "quadratic-forms", "local-global", "rational-functions"]
defaultTargets = ["RatFuncWittLocalGlobal"]
fixedToolchain = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.overlappingInstances = false
maxSynthPendingDepth = 3
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "RatFuncWittLocalGlobal"
